myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('seller-index/',views.seller_index,name="seller-index"),
    path('about/',views.about,name="about"),
    path('contact/',views.contact,name="contact"),
    path('register/',views.register,name="register"),   
    path('login/',views.login,name="login"),    
    path('logout/',views.logout,name="logout"),   
    path('change-password/',views.change_password,name="change-password"),
    path('profile/',views.profile,name="profile"),
    path('forgot-password/',views.forgot_password,name="forgot-password"),
    path('verify-otp/',views.verify_otp,name="verify-otp"),
    path('new-password/',views.new_password,name="new-password"),

    path('add-product/',views.add_product,name="add-product"),
    path('delete-product/<int:pk>/',views.delete_product,name="delete-product"),
    path('edit-product/<int:pk>/',views.edit_product, name='edit-product'),
    path('seller-single-product/<int:pk>/',views.seller_single_product, name='seller-single-product'),
    path('shop/',views.shop,name="shop"),
    path('search/',views.search,name="search"),
    path('single-product/<int:pk>',views.single_product,name="single-product"),
    path('add-to-cart/<int:pk>',views.add_to_cart,name="add-to-cart"),
    path('cart/',views.cart,name="cart"),
    path('remove-from-cart/<int:pk>',views.remove_from_cart,name="remove-from-cart"),
    path('change-qty/',views.change_qty,name="change-qty"),
    path('add-to-wishlist/<int:pk>',views.add_to_wishlist,name="add-to-wishlist"),
    path('wishlist/',views.wishlist,name="wishlist"),
    path('remove-from-wishlist/<int:pk>',views.remove_from_wishlist,name="remove-from-wishlist"),
    path('create-checkout-session',views.create_checkout_session,name="payment"),
    path('success.html/',views.success,name="success"),
    path('cancel.html/',views.cancel,name="cancel"),
    path('myorder/',views.myorder,name="myorder"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Contact(models.Model):
	name=models.CharField(max_length=50)
	email=models.EmailField()
	subject=models.CharField(max_length=100)
	message=models.TextField()

	def __str__(self):
		return self.name

class User(models.Model):
	username=models.CharField(max_length=100)
	email=models.EmailField()
	mobile=models.PositiveIntegerField()
	password=models.CharField(max_length=50)
	usertype=models.CharField(max_length=50,default="buyer")

	def __str__(self):
		return self.username

class Category(models.Model):
	name=models.CharField(max_length=200)

	def __str__(self):
		return self.name

class Brand(models.Model):
	name=models.CharField(max_length=200)

	def __str__(self):
		return self.name

class Color(models.Model):
	code=models.CharField(max_length=50)

	def __str__(self):
		return self.code

class Filter_Price(models.Model):
	FILTER_PRICE=(
		('1000_TO_10000','1000_TO_10000'),
		('10000_TO_20000','10000_TO_20000'),
		('20000_TO_30000','20000_TO_30000'),
		('30000_TO_40000','30000_TO_40000'),
		('40000_TO_50000','40000_TO_50000'),
	)

	price=models.CharField(choices=FILTER_PRICE,max_length=50)

	def __str__(self):
		return self.price

class Product(models.Model):
	CONDITION=(
		('new','new'),
		('old','old'),
	)

	STOCK=(
		('In_Stock','In_Stock'),
		('Out_Of_Stock','Out_Of_Stock'),
	)

	seller=models.ForeignKey(User,on_delete=models.CASCADE, related_name='seller_products')
	category=models.ForeignKey(Category,on_delete=models.CASCADE)
	brand=models.ForeignKey(Brand,on_delete=models.CASCADE)
	color=models.ForeignKey(Color,on_delete=models.CASCADE)
	filter_price=models.ForeignKey(Filter_Price,on_delete=models.CASCADE)
	name=models.CharField(max_length=200)
	price=models.IntegerField()
	m_image=models.ImageField(upload_to="product_image/")
	condition=models.CharField(choices=CONDITION,max_length=50)
	stock=models.CharField(choices=STOCK,max_length=50)
	info=models.TextField()
	desc=models.TextField()
	date=models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.name

class SliderImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="slider_images/")

    def __str__(self):
    	return self.product.name+"- Sub Image"

class Cart(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	product=models.ForeignKey(Product,on_delete=models.CASCADE)
	date=models.DateTimeField(default=timezone.now)
	product_price=models.PositiveIntegerField()
	product_qty=models.PositiveIntegerField()
	total_price=models.PositiveIntegerField()
	payment_status=models.BooleanField(default=False)

	def __str__(self):
		return self.user.username+" - "+self.product.name

class Wishlist(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	product=models.ForeignKey(Product,on_delete=models.CASCADE)
	date=models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.user.username+" - "+self.product.name

myapp/views.py
from django.shortcuts import render,redirect
from myapp. models import *
from django.conf import settings
from django.core.mail import send_mail
import random

from django.http import JsonResponse,HttpResponse
from django.views.decorators.csrf import csrf_exempt
import json
import stripe

stripe.api_key = settings.STRIPE_PRIVATE_KEY
YOUR_DOMAIN = 'http://localhost:8000'


def index(request):
	product=Product.objects.all()
	try:
		user=User.objects.get(email=request.session['email'])
		if user.usertype=="buyer":
			return render(request,'index.html',{'product':product})
		else:
			return redirect('seller-index') 
	except:
		return render(request,'index.html',{'product':product})


def seller_index(request):
	seller=User.objects.get(email=request.session['email'])
	product=Product.objects.filter(seller=seller)
	return render(request, 'seller-index.html',{'product':product})

def about(request):
	return render(request,'about.html')

def contact(request):
    if request.method=="POST":
        Contact.objects.create(
                name=request.POST['name'],
                email=request.POST['email'],
                subject=request.POST['subject'],
                message=request.POST['message']
            )
        msg="Contact Added Sucssesfully."
        return render(request,'contact.html',{'msg':msg})
    else:
        return render(request,'contact.html')

def register(request):
    if request.method=="POST":
        try:
            User.objects.get(email=request.POST['email'])
            msg="Email is Already Registered."
            return render(request,'login.html',{'msg':msg})
        except:
            if request.POST['password']==request.POST['cpassword']:
                User.objects.create(
                		usertype=request.POST['usertype'],
                        username=request.POST['username'],
                        email=request.POST['email'],
                        mobile=request.POST['mobile'],
                        password=request.POST['password']
                    )
                msg="Your Registration Sucssesfully Done."
                return render(request,'login.html',{'msg':msg})
            else:
                msg="Password & Confirm Password Does Not Matched"
                return render(request,'login.html',{'msg':msg})
    else:
        return render(request,'login.html')

def login(request):
    if request.method == "POST":
        try:
            user = User.objects.get(email=request.POST['email'])
            if user.password == request.POST['password']:
                if user.usertype == "buyer":
                    request.session['email'] = user.email
                    request.session['username'] = user.username
                    carts=Cart.objects.filter(user=user)
                    request.session['cart_count']=len(carts)
                    wishlists=Wishlist.objects.filter(user=user)
                    request.session['wishlist_count']=len(wishlists)
                    return redirect('index')
                else:
                    request.session['email'] = user.email
                    request.session['username'] = user.username
                    return redirect('seller-index')
            else:
                msg = "Password Is Incorrect"
                return render(request, 'login.html', {'msg': msg})
        except:
            msg = "Email Not Registered"
            return render(request, 'login.html', {'msg': msg})
    else:
        return render(request, 'login.html')


def logout(request):
    try:
        del request.session['email']
        del request.session['username']
        msg="User Logged Out Successfully"
        return render(request,'login.html',{'msg':msg})
    except:
        return render(request,'login.html')

def change_password(request):
    user = User.objects.get(email=request.session['email'])
    if request.method=="POST":
        if user.password==request.POST['old_password']:
            if request.POST['new_password']==request.POST['cnew_password']:
                user.password=request.POST['new_password']
                user.save()
                return redirect('logout')
            else:
                msg="New Password & Confirm New Password Does Not Matched"
                if user.usertype=="buyer":
                	return render(request,'change-password.html',{'msg':msg})
                else:
                	return render(request,'seller-change-password.html',{'msg':msg})
        else:
            msg="Old Password is Incoreect"
            if user.usertype=="buyer":
            	return render(request,'change-password.html',{'msg':msg})
            else:
            	return render(request,'seller-change-password.html',{'msg':msg})
    else:
        if user.usertype=="buyer":
        	return render(request,'change-password.html')
        else:
            return render(request,'seller-change-password.html')


def profile(request):
    user = User.objects.get(email=request.session['email'])
    if request.method == "POST":
        user.username = request.POST['username']
        user.mobile = request.POST['mobile']
        user.save()
        msg = "Profile Updated Successfully."
        if user.usertype == "buyer":
            return render(request, 'profile.html', {'user': user, 'msg': msg})
        else:
            return render(request, 'seller-profile.html', {'user': user, 'msg': msg})
    else:
        if user.usertype == "buyer":
            return render(request, 'profile.html', {'user': user})
        else:
            return render(request, 'seller-profile.html', {'user': user})

def forgot_password(request):
    if request.method=="POST":
        try:
            user=User.objects.get(email=request.POST['email'])
            otp=random.randint(10000,99999)
            subject = 'OTP for Forgot Password'
            message = 'Hello! '+user.username+', Your OTP for Forgot Password is : '+str(otp)
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [user.email, ]
            send_mail( subject, message, email_from, recipient_list )
            return render(request,'otp.html',{'email':user.email,'otp':otp})
        except:
            msg="Email Not Registered ."
            return render(request,'forgot-password.html',{'msg':msg})
    else:
        return render(request,'forgot-password.html')

def verify_otp(request):
    email=request.POST['email']
    otp=int(request.POST['otp'])
    uotp=int(request.POST['uotp'])

    if otp==uotp:
        return render(request,'new-password.html',{'email':email})
    else:
        msg="Invalid OTP"
        return render(request,'otp.html',{'email':email,'otp':otp,'msg':msg})

def new_password(request):
    email=request.POST['email']
    np=request.POST['new_password']
    cnp=request.POST['cnew_password']

    if np==cnp:
        user=User.objects.get(email=email)
        user.password=np
        user.save()
        msg="Your Password Updated Successfully."
        return render(request,'login.html',{'msg':msg})
    else:
        msg="New Password & Confirm New Password Does Not Matched."
        return render(request,'new-password.html',{'msg':msg,'email':email})

def add_product(request):
    seller = User.objects.get(email=request.session['email'])
    if request.method == 'POST':
        category_name = request.POST['category']
        brand_name = request.POST['brand']
        color_code = request.POST['code']
        filter_price=request.POST['filter_price']

        category, created = Category.objects.get_or_create(name=category_name)
        brand, created = Brand.objects.get_or_create(name=brand_name)
        color, created = Color.objects.get_or_create(code=color_code)
        price, created = Filter_Price.objects.get_or_create(price=filter_price)

        product = Product.objects.create(
            seller=seller,
            category=category,
            brand=brand,
            color=color,
            filter_price=price,
            name=request.POST['name'],
            price=request.POST['price'],
            condition=request.POST['condition'],
            stock=request.POST['stock'],
            info=request.POST['info'],
            desc=request.POST['desc'],
            m_image=request.FILES.get('image')
        )

        for i in range(1, 4):
            image_key = f'image{i}'
            if image_key in request.FILES:
                SliderImage.objects.create(product=product, image=request.FILES[image_key])

        msg = "Product Added Successfully"
        return render(request, 'add-product.html', {'msg': msg})
    else:
        return render(request, 'add-product.html')


def delete_product(request,pk):
	product=Product.objects.get(pk=pk)
	product.delete()
	return redirect('seller-index')

def edit_product(request, pk):
    products = Product.objects.get(pk=pk)
    if request.method == 'POST':
        category = request.POST.get('category')
        filter_price = request.POST.get('filter_price')
        brand = request.POST.get('brand')
        condition = request.POST.get('condition')
        code = request.POST.get('code')
        stock = request.POST.get('stock')
        name = request.POST.get('name')
        price = request.POST.get('price')
        
        info = request.POST.get('info')
        desc = request.POST.get('desc')

        category, created = Category.objects.get_or_create(name=category)
        brand, created = Brand.objects.get_or_create(name=brand)
        color, created = Color.objects.get_or_create(code=code)
        filter_price, created = Filter_Price.objects.get_or_create(price=filter_price)

        products.category = category
        products.filter_price = filter_price
        products.brand = brand
        products.condition = condition
        products.color = color
        products.stock = stock
        products.name = name
        products.price = price
        products.info = info
        products.desc = desc
        try:

myapp/templates/edit-product.html
{% extends 'seller-header.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="zxx" dir="ltr">

<head>

</head>

<body>

    <div class="breadcrumb-area">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-12 text-center">
                    <h2 class="breadcrumb-title">Update Product</h2>
                    <!-- breadcrumb-list start -->
                    <ul class="breadcrumb-list">
                        <li class="breadcrumb-item"><a href="{% url 'seller-index' %}">Home</a></li>
                        <li class="breadcrumb-item active">Update Product</li>
                    </ul>
                    <!-- breadcrumb-list end -->
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb-area end -->
    <!-- Contact Area Start -->
    <div class="contact-area">
        <div class="container">
            <div class="contact-wrapper">
                <div class="row">
                    <div class="col-12">
                        <div class="contact-form">
                            <div class="container">
                                {% if msg %}
                                <center>
                                    <div class="alert alert-success">
                                        <strong>{{msg}}</strong>
                                    </div>
                                </center>
                                {% endif %}
                                <form action="{% url 'edit-product' pk=products.pk %}" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-lg-6 col-md-6">
                                            <input name="category" placeholder="Product category" type="text" value="{{products.category}}">
                                        </div>
                                        <div class="col-lg-6 col-md-6">
                                            <select name="filter_price" required>
                                                <option value="{{products.filter_price}}">{{products.filter_price}}</option>
                                                <option value="1000_TO_10000">1000 TO 10000</option>
                                                <option value="10000_TO_20000">10000 TO 20000</option>
                                                <option value="20000_TO_30000">20000 TO 30000</option>
                                                <option value="30000_TO_40000">30000 TO 40000</option>
                                                <option value="40000_TO_50000">40000 TO 50000</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-6 col-md-6">
                                            <input name="brand" placeholder="Product brand" type="text" value="{{products.brand}}" required>
                                        </div>
                                        <div class="col-lg-6 col-md-6">
                                            <select name="condition" required>
                                                <option value="{{products.condition}}">{{products.condition}}</option>
                                                <option value="new">NEW</option>
                                                <option value="old">OLD</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-6 col-md-6">
                                            <input name="code" placeholder="Product Color Code" type="text" value="{{products.color}}" required>
                                        </div>
                                        <div class="col-lg-6 col-md-6">
                                            <select name="stock" required>
                                                <option value="{{products.stock}}">{{products.stock}}</option>
                                                <option value="In_Stock">IN STOCK</option>
                                                <option value="Out_Of_Stock">OUT OF STOCK</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-6 col-md-6">
                                            <input name="name" placeholder="Product Name" type="text" value="{{products.name}}" required>
                                        </div>
                                        <div class="col-lg-6 col-md-6">
                                            <input name="price" placeholder="Product Price" type="text" value="{{products.price}}" required>
                                        </div>
                                        <div class="col-lg-12 col-md-6">
                                            <label style="color: blue;">* Main Image For Your Product : </label>
                                        </div>
                                         <div class="col-lg-12 col-md-6">
                                            <img src="{{ products.m_image.url }}" style="width: 100px; height: 100px;">
                                        </div>
                                        <div class="col-lg-12 col-md-6">
                                            <input name="image" type="file">
                                        </div>
                                        <div class="col-lg-12 col-md-6">
                                            <label style="color: blue;">* Upload More Images For Your Product : </label>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <img src="{{ products.sliderimage_set.all.0.image.url }}" width="100vh" height="100vh">
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <img src="{{ products.sliderimage_set.all.1.image.url }}" width="100vh" height="100vh">
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <img src="{{ products.sliderimage_set.all.2.image.url }}" width="100vh" height="100vh">
                                        </div>
                                        <div  class="col-lg-4">
                                            <input name="image1" type="file">
                                        </div>
                                        <div  class="col-lg-4">
                                            <input name="image2" type="file">
                                        </div>
                                        <div  class="col-lg-4">
                                            <input name="image3" type="file">
                                        </div>
                                        <div class="col-lg-12 text-center">
                                            <textarea name="info" placeholder="Product Information" required>{{products.info}}</textarea>
                                        </div>
                                        <div class="col-lg-12 text-center">
                                            <textarea name="desc" placeholder="Product Description" required>{{products.desc}}</textarea>
                                        </div>
                                        <div class="col-lg-12 text-center">
                                            <button class="btn btn-primary" type="submit">Update Product</button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

{% endblock %}

myapp/templates/forgot-password.html
{% extends 'header.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="zxx" dir="ltr">

<head>
    
</head>

<body>
        <!-- login area start -->
        <div class="login-register-area pt-100px pb-100px">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-12 ml-auto mr-auto">
                        <div class="login-register-wrapper">
                            <div class="login-register-tab-list nav">
                                    <h4>Forgot Password</h4>
                            </div>
                            <div class="tab-content">
                                <div id="lg1" class="tab-pane active">
                                    <div class="login-form-container">
                                        <div class="login-register-form">
                                            {% if msg %}
                                              <center>
                                                <div class="alert alert-success">
                                                  <strong>{{msg}}</strong>
                                                </div>
                                              </center>
                                            {% endif %}
                                            <form action="{% url 'forgot-password' %}" method="post">
                                                {% csrf_token %}
                                                <input type="email" name="email" placeholder="Enter email" />
                                                <div class="button-box">
                                                    <center>
                                                        <button type="submit"><span>Send OTP</span></button>
                                                    </center>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- login area end -->

</body>

</html>

{% endblock %}

myapp/templates/seller-single-product.html
{% extends 'seller-header.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="zxx" dir="ltr">


<head>
    
</head>

<body>
    
        <!-- Product Details Area Start -->
        <div class="product-details-area pt-100px pb-100px">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-sm-12 col-xs-12 mb-lm-30px mb-md-30px mb-sm-30px">
                        <!-- Swiper -->
                        <div class="swiper-container zoom-top">
                            <div class="swiper-wrapper">
                                {% for i in single.sliderimage_set.all %}
                                <div class="swiper-slide">
                                    <img class="img-responsive m-auto" src="{{i.image.url}}" alt="">
                                    <a class="venobox full-preview" data-gall="myGallery" href="{{i.image.url}}">
                                        <i class="fa fa-arrows-alt" aria-hidden="true"></i>
                                    </a>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="swiper-container mt-20px zoom-thumbs slider-nav-style-1 small-nav">
                            <div class="swiper-wrapper">
                                {% for i in single.sliderimage_set.all %}
                                <div class="swiper-slide">
                                    <img class="img-responsive m-auto" src="{{i.image.url}}" alt="">
                                </div>
                                {% endfor %}
                            </div>
                            <!-- Add Arrows -->
                            <div class="swiper-buttons">
                                <div class="swiper-button-next"></div>
                                <div class="swiper-button-prev"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-12 col-xs-12" data-aos="fade-up" data-aos-delay="200">
                        <div class="product-details-content quickview-content ml-25px">
                            <h2>{{single.name}}</h2>
                            <div class="pricing-meta">
                                <ul class="d-flex">
                                    <li class="new-price">₹ {{single.price}}</li>
                                </ul>
                            </div>
                            <!-- <div class="pro-details-rating-wrap">
                                <div class="rating-product">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>
                                <span class="read-review"><a class="reviews" href="#">(5 Customer Review)</a></span>
                            </div> -->
                            <p class="mt-30px">{{single.info}}</p>

                            <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                                <span>Categories: </span>
                                <ul class="d-flex">
                                    <li>
                                        <a href="#">{{single.category}}</a>
                                    </li>
                                </ul>
                            </div>
                            
                        </div>
                        <!-- product details description area start -->
                        <div class="description-review-wrapper">
                            <div class="description-review-topbar nav">
                                <button class="active" data-bs-toggle="tab" data-bs-target="#des-details2">Information</button>
                                <button data-bs-toggle="tab" data-bs-target="#des-details1">Description</button>
                                <button data-bs-toggle="tab" data-bs-target="#des-details3">Reviews (02)</button>
                            </div>
                            <div class="tab-content description-review-bottom">
                                <div id="des-details2" class="tab-pane">
                                    <div class="product-anotherinfo-wrapper text-start">
                                        <ul>
                                            {{single.info}}
                                        </ul>
                                    </div>
                                </div>
                                <div id="des-details1" class="tab-pane active">
                                    <div class="product-description-wrapper">
                                        <p>
                                            {{single.desc}}
                                        </p>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <!-- product details description area end -->
                    </div>
                </div>
            </div>
        </div>
</body>

</html>

{% endblock %}